name: AWS ECS Continuous Deployment

on:
  workflow_run:
    workflows: ['Docker Build & Push']
    branches: [main]
    types:
      - completed

jobs:
  deploy-to-aws:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Download Active Task Definitions
        run: |
          aws ecs describe-task-definition --task-definition perpx-web-task --query taskDefinition > task-def-web.json
          aws ecs describe-task-definition --task-definition perpx-api-task --query taskDefinition > task-def-api.json

      - name: Render New Frontend Task Definition
        id: render-web
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-web.json
          container-name: perpx-web-container
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/perpx-web:latest

      - name: Render New Backend Task Definition
        id: render-api
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-api.json
          container-name: perpx-api-container
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/perpx-api:latest

      - name: Deploy Frontend to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-web.outputs.task-definition }}
          service: perpx-web-task-service-7l7750w7
          cluster: perpx-cluster
          wait-for-service-stability: true

      - name: Deploy Backend API to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-api.outputs.task-definition }}
          service: perpx-api-task-service-b7egg20l
          cluster: perpx-cluster
          wait-for-service-stability: true
